@endpoint = http://localhost:5000/api/v1/cars

###
GET http://localhost:5000/api/v1/cars HTTP/1.1
content-type: application/json
x-api-key: blahblah


###
# @name PostACar
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
  "make": "Ford",
  "model": "F-15"
}

###

@newCar = {{PostACar.response.body._id}}

###
GET  {{endpoint}} HTTP/3.0
content-type: application/json

###
GET  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json


###

DELETE  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json

###

PUT  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json
